import os
import re
import json
import random
import datetime
from langchain_openai import ChatOpenAI
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import JsonOutputParser
from app.config import settings

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_JUSTIFY, TA_CENTER

def _header_footer(canvas, doc):
    canvas.saveState()
    canvas.setFont('Helvetica-Bold', 8)
    canvas.drawRightString(A4[0] - inch, A4[1] - 0.75 * inch, "WAKEEL-AI | AI-Powered Legal Assistant")
    
    canvas.setFont('Helvetica', 8)
    footer_text = f"Generated by Wakeel-AI | Page {doc.page} | Not a substitute for legal advice"
    canvas.drawCentredString(A4[0] / 2.0, 0.75 * inch, footer_text)
    canvas.restoreState()

class DocumentSpecialistAgent:
    def __init__(self):
        from app.agent.core.llm import get_resilient_llm
        self.llm = get_resilient_llm(temperature=0, max_tokens=2000)

    def select_template(self, issue_type: str) -> str:
        """Maps Agent 1 output issue_type to correct template file"""
        mapping = {
            "khula": "khula_petition.txt",
            "talaq": "talaq_notice.txt",
            "maintenance": "maintenance_petition.txt",
            "custody": "custody_petition.txt",
            "dissolution": "dissolution_petition.txt",
            "dowry": "dowry_petition.txt",
            "parents_rights": "parents_maintenance_petition.txt"
        }
        filename = mapping.get(issue_type.lower(), "khula_petition.txt")
        base_dir = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
        return os.path.join(base_dir, "data", "templates", filename)

    def extract_placeholders(self, legal_brief: dict, chat_history: str, required_keys: list) -> dict:
        """Call Gemini to extract values for placeholders from the chat history"""
        prompt = ChatPromptTemplate.from_template("""
You are a document assistant for Pakistani family court petitions.

Given this legal brief from the Legal Analyst Agent:
{legal_brief}

And the conversation history between the user and the agent:
{chat_history}

Extract values for these placeholders based on the conversation and brief.
Required fields to extract:
{required_keys_list}

For each required field:
- If the value is found in the conversation or the legal brief, extract it exactly.
- For any value not found in the conversation or legal brief, use exactly "[TO BE PROVIDED]".
- If the user explicitly states they don't have the info, don't know it, or want to skip it, use exactly "[SKIPPED]".
Never leave any field empty.
Return ONLY a valid JSON object where the keys are exactly the required fields listed above, and the values are the extracted values. No explanation or formatting wrappers.
""")
        chain = prompt | self.llm | JsonOutputParser()
        try:
            required_keys_list = "\n".join([f"- {k}" for k in required_keys])
            result = chain.invoke({
                "legal_brief": json.dumps(legal_brief),
                "chat_history": chat_history,
                "required_keys_list": required_keys_list
            })
            return result
        except Exception as e:
            print(f"Error extracting placeholders: {e}")
            return {}

    def ask_for_missing_info(self, missing_fields: list, chat_history: str) -> str:
        """Generates a conversational question asking the user for missing fields."""
        prompt = ChatPromptTemplate.from_template("""
You are 'Wakeel-AI', a helpful legal assistant drafting a court petition.
The following fields are still missing to complete the document:
{missing_fields}

Conversation so far:
{chat_history}

Generate a polite, empathetic, and professional question asking the user for 1 or 2 of these missing fields. 
DO NOT ask for all of them at once if there are many. Just pick the most important ones (like names, CNIC, or dates).
Tell them they can say "I don't know" or "Skip" if they don't have the information and we will leave it blank for now.
Respond directly with the question.
""")
        chain = prompt | self.llm
        try:
            result = chain.invoke({"missing_fields": ", ".join(missing_fields), "chat_history": chat_history})
            return result.content.strip()
        except Exception as e:
            return f"To complete your petition, I still need a few details: {', '.join(missing_fields[:2])}. Could you provide them? (You can skip if you don't know)"

    def fill_and_validate(self, template_path: str, placeholders: dict) -> tuple[str, list]:
        try:
            with open(template_path, 'r', encoding='utf-8') as f:
                template_content = f.read()
        except FileNotFoundError:
            return f"Template {template_path} not found.", []

        filled_text = template_content
        missing_fields = []
        
        matches = re.findall(r'\{\{(.*?)\}\}', template_content)
        
        for key in matches:
            val = placeholders.get(key, "[TO BE PROVIDED]")
            
            if val == "[TO BE PROVIDED]":
                if key not in missing_fields:
                    missing_fields.append(key)
            elif val == "[SKIPPED]":
                val = "_________________" # Leave empty space for user to fill later
                    
            filled_text = filled_text.replace(f"{{{{{key}}}}}", str(val))
            
        return filled_text, missing_fields

    def generate_pdf(self, filled_text: str, case_id: str, issue_type: str) -> str:
        base_dir = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
        output_dir = os.path.join(base_dir, "data", "output")
        
        try:
            os.makedirs(output_dir, exist_ok=True)
            test_file = os.path.join(output_dir, ".write_test")
            with open(test_file, "w") as f:
                f.write("test")
            os.remove(test_file)
        except Exception:
            import tempfile
            output_dir = os.path.join(tempfile.gettempdir(), "wakeel_output")
            os.makedirs(output_dir, exist_ok=True)
            
        pdf_path = os.path.join(output_dir, f"{case_id}_{issue_type}.pdf")
        
        doc = SimpleDocTemplate(
            pdf_path,
            pagesize=A4,
            rightMargin=inch,
            leftMargin=inch,
            topMargin=inch,
            bottomMargin=inch
        )
        
        styles = getSampleStyleSheet()
        title_style = ParagraphStyle(
            'TitleStyle',
            parent=styles['Heading1'],
            fontName='Helvetica-Bold',
            fontSize=13,
            alignment=TA_CENTER,
            spaceAfter=14
        )
        
        body_style = ParagraphStyle(
            'BodyStyle',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=10,
            alignment=TA_JUSTIFY,
            leading=14,
            spaceAfter=10
        )
        
        heading_style = ParagraphStyle(
            'SectionHeading',
            parent=styles['Heading2'],
            fontName='Helvetica-Bold',
            fontSize=11,
            spaceAfter=10,
            spaceBefore=10
        )

        elements = []
        paragraphs = filled_text.split('\n\n')
        
        for p in paragraphs:
            p = p.strip()
            if not p:
                continue
                
            if "======" in p:
                clean_p = re.sub(r'=+', '', p).strip()
                elements.append(Paragraph(clean_p, title_style))
            elif p.isupper() and len(p) < 60 and not "---" in p:
                elements.append(Paragraph(p, heading_style))
            else:
                p_text = p.replace('\n', '<br/>')
                elements.append(Paragraph(p_text, body_style))
        
        doc.build(elements, onFirstPage=_header_footer, onLaterPages=_header_footer)
        return pdf_path

    def _mock_court_filing(self, issue_type: str, city: str) -> dict:
        court_codes = {
            "Karachi": "KHI", "Lahore": "LHR",
            "Islamabad": "ISB", "Rawalpindi": "RWP",
            "Peshawar": "PSH", "Quetta": "QTA"
        }
        code = court_codes.get(city, "PKT")
        year = datetime.datetime.now().year
        ref = f"FC-{code}-{year}-{random.randint(1000,9999)}"
        return {
            "case_ref": ref,
            "filed_at": datetime.datetime.now().isoformat(),
            "court": f"Family Court {city}",
            "status": "Submitted (Simulated)"
        }

    def process(self, legal_brief: dict, chat_history: str, case_id: str, question_round: int = 0) -> dict:
        issue_type = legal_brief.get("issue_type", "khula") if isinstance(legal_brief, dict) else "khula"
        template_path = self.select_template(issue_type)
        
        # Read the template first to dynamically find all placeholder keys
        try:
            with open(template_path, 'r', encoding='utf-8') as f:
                template_content = f.read()
            required_keys = list(set(re.findall(r'\{\{(.*?)\}\}', template_content)))
        except Exception:
            required_keys = ["WIFE_NAME", "HUSBAND_NAME", "CITY", "COURT_NAME", "YEAR", "DATE"]

        # Call Gemini to extract only the placeholders that are actually in the template
        placeholders = self.extract_placeholders(legal_brief, chat_history, required_keys)
        
        # Auto-fill system fields if they are missing or still "[TO BE PROVIDED]"
        current_year = str(datetime.datetime.now().year)
        today_date = datetime.date.today().strftime("%B %d, %Y")
        
        system_defaults = {
            "YEAR": current_year,
            "DATE": today_date,
            "DEFAULT_DATE": today_date,
        }
        
        city = placeholders.get("CITY", "[TO BE PROVIDED]")
        if city not in ["[TO BE PROVIDED]", "[SKIPPED]"]:
            system_defaults["COURT_NAME"] = f"Family Court of {city}"
            
        if placeholders.get("ADVOCATE_NAME") in ["[TO BE PROVIDED]", None]:
            system_defaults["ADVOCATE_NAME"] = "Self-Represented"
            
        for k, v in system_defaults.items():
            if placeholders.get(k) in ["[TO BE PROVIDED]", None]:
                placeholders[k] = v

        filled_text, missing_fields = self.fill_and_validate(template_path, placeholders)
        
        # Calculate filled fields
        filled_fields_count = sum(1 for v in placeholders.values() if v not in ["[TO BE PROVIDED]", "[SKIPPED]"])
        total_fields_count = len(placeholders)
        document_type = issue_type.replace('_', ' ').title() + " Petition"
        
        # Only ask for missing info if we haven't exceeded 3 question rounds
        MAX_QUESTION_ROUNDS = 3
        if len(missing_fields) > 0 and question_round < MAX_QUESTION_ROUNDS:
            question = self.ask_for_missing_info(missing_fields, chat_history)
            return {
                "status": "missing_info",
                "question": question,
                "missing_fields": missing_fields,
                "filled_fields_count": filled_fields_count,
                "total_fields_count": total_fields_count,
                "document_type": document_type
            }
            
        # Clean remaining "[TO BE PROVIDED]" placeholders into clean underscores/blanks for a premium look
        final_filled_text = filled_text.replace("[TO BE PROVIDED]", "_________________")
        
        pdf_path = self.generate_pdf(final_filled_text, case_id, issue_type)
        
        city = placeholders.get("CITY", "Unknown")
        if city in ["[TO BE PROVIDED]", "[SKIPPED]"]:
            city = "Unknown"
            
        mock_filing = self._mock_court_filing(issue_type, city)
        
        # Calculate filled fields (extracted ones that are not [TO BE PROVIDED])
        filled_fields_count = sum(1 for v in placeholders.values() if v != "[TO BE PROVIDED]")
        total_fields_count = len(placeholders)
        
        document_type = issue_type.replace('_', ' ').title() + " Petition"
        
        reasoning_steps = [
            f"Selected {os.path.basename(template_path)} based on issue_type: {issue_type}",
            f"Extracted {filled_fields_count} of {total_fields_count} placeholder values from legal brief",
            f"{len(missing_fields)} fields marked as [TO BE PROVIDED] — left as blanks",
            f"PDF generated: {pdf_path}",
            f"Mock filing submitted — Ref: {mock_filing['case_ref']}"
        ]
        
        return {
            "status": "success",
            "pdf_path": pdf_path,
            "document_type": document_type,
            "missing_fields": missing_fields,
            "filled_fields_count": filled_fields_count,
            "total_fields_count": total_fields_count,
            "mock_filing": mock_filing,
            "reasoning_steps": reasoning_steps
        }
