"""add_cases_messages_documents

Revision ID: 1c9bb6ae7d86
Revises: cc7ccd6d3f6b
Create Date: 2026-05-17 21:42:33.108149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c9bb6ae7d86'
down_revision: Union[str, Sequence[str], None] = 'cc7ccd6d3f6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
