"""add cnic to users

Revision ID: 9b96886c4539
Revises: f3f4179248a2
Create Date: 2026-05-20 01:40:08.122675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b96886c4539'
down_revision: Union[str, Sequence[str], None] = 'f3f4179248a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cnic', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_users_cnic'), 'users', ['cnic'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_cnic'), table_name='users')
    op.drop_column('users', 'cnic')
    # ### end Alembic commands ###
